version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'team21_v1'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  backend:
    build: .
    restart: on-failure
    depends_on:
      - db
      # db:
      #   condition: service_healthy
    entrypoint: ['python', 'backend_main.py']

  web:
    build: .
    ports:
      - '8050:8050'
    entrypoint:
      - /bin/sh
      - -c
      - |
        while [ "$(docker inspect -f '{{.State.Running}}' backend)" = "true" ]; do
          sleep 5;
        done;
        /usr/wait-for-it.sh db:3306 --timeout=100 -- python main.py
