version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'team21_v1'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'

  web:
    build: .
    ports:
      - "8050:8050"
    depends_on:
      - db
    entrypoint: ["/usr/wait-for-it.sh", "db:3306", "--timeout=400", "--strict", "--", "python", "main.py"]


