version: '1.29'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'team21_v1'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  backend:
    build: .
    restart: always
    ports:
      - '3308:3308'
    depends_on:
      - db
      # db:
      #   condition: service_completed_successfully
        # condition: service_healthy
        # healthcheck:
        #   test: ["CMD", "curl", "-f", "http://db:3306/readiness"]
        #   interval: 10s
        #   timeout: 10s
        #   retries: 5

    entrypoint: ["/usr/wait-for-it.sh", "db:3306", "--timeout=100", "--strict", "--", 'python','backend_main.py']
  web:
    build: .
    ports:
      - "8050:8050"
    depends_on:
      - backend
      # backend:
      #   condition: service_completed_successfully
        # healthcheck:
        #   test: ["CMD", "curl", "-f", "http://db:3306/readiness"]
        #   interval: 10s
        #   timeout: 10s
        #   retries: 5
    entrypoint: ["/usr/wait-for-it.sh", "backend:3308", "--timeout=100", "--strict", "--", "python", "main.py"]


