version: '1.29'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'team21_v1'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  backend:
    build: .
    ports:
      - '3308:3308'
    depends_on:
      - db
    entrypoint: ["/usr/wait-for-it.sh", "db:3306", "--timeout=100", "--strict", "--", 'python','backend_main.py']
  
  web:
    build: .
    ports:
      - "8050:8050"
    depends_on:     
      backend:
        condition: service_completed_successfully
    entrypoint: ["python", "main.py"]

